const { Modal, Plugin, Setting, MarkdownView, requestUrl } = require('obsidian');

const DEFAULT_SETTINGS = {
    icons: {} // Maps "iconName" -> "filename.png"
};

const ALLOWED_IMAGE_TYPES = ['image/png', 'image/jpeg', 'image/jpg', 'image/webp', 'image/gif', 'image/svg+xml'];

module.exports = class NotionIconPlugin extends Plugin {
    async onload() {
        await this.loadSettings();
        await this.ensureIconFolder();
        
        // Runtime in-memory cache for folder icons to keep sidebar rendering blazing fast
        this.folderIconsCache = {}; 
        await this.scanVaultForFolderIcons();
        await this.generateDynamicCssSnippet(); 

        // Ribbon Icon Launcher
        this.addRibbonIcon('image-plus', 'Notion-like Icon Manager', () => {
            new CentralIconLibraryModal(this.app, this).open();
        });

        // Command Palette Hooks
        this.addCommand({
            id: 'open-icon-manager',
            name: 'Open Global Icon Library Manager',
            callback: () => {
                new CentralIconLibraryModal(this.app, this).open();
            }
        });

        this.addCommand({
            id: 'add-notion-icon',
            name: 'Configure Current Note Icon',
            callback: () => {
                const activeFile = this.app.workspace.getActiveFile();
                if (activeFile) {
                    new UniversalIconPickerModal(this.app, this, { type: 'note', target: activeFile }).open();
                } else {
                    alert("Please open a note first!");
                }
            }
        });

        // Right-Click Folder Context Menu Hook
        this.registerEvent(
            this.app.workspace.on('file-menu', (menu, abstractFile) => {
                if (abstractFile.children) {
                    menu.addItem((item) => {
                        item.setTitle('Configure Folder Icon')
                            .setIcon('folder')
                            .onClick(() => {
                                new UniversalIconPickerModal(this.app, this, { type: 'folder', target: abstractFile }).open();
                            });
                    });
                }
            })
        );

        // Dynamic Layout Observer
        this.observer = new MutationObserver((mutations) => {
            for (let mutation of mutations) {
                for (let node of mutation.addedNodes) {
                    if (node.nodeType === Node.ELEMENT_NODE) {
                        this.applyShortcodeAttributes(node);
                    }
                }
            }
        });

        this.observer.observe(document.body, { childList: true, subtree: true });

        this.registerEvent(this.app.workspace.on('layout-change', () => this.refreshAllDisplays()));
        this.registerEvent(this.app.workspace.on('file-open', () => this.refreshAllDisplays()));
        this.registerEvent(this.app.metadataCache.on('changed', () => this.refreshAllDisplays()));

        this.app.workspace.onLayoutReady(() => {
            this.applyShortcodeAttributes(document.body);
            this.refreshAllDisplays();
        });
    }

    onunload() {
        if (this.observer) this.observer.disconnect();
    }

    // CONSTANT PATH: Always points exactly to your vault root directory
    getIconFolderPath() { 
        return '.notion-like-icons'; 
    }

    async ensureIconFolder() {
        const path = this.getIconFolderPath();
        if (!(await this.app.vault.adapter.exists(path))) {
            await this.app.vault.adapter.mkdir(path);
        }
    }

    getIconSrcPath(filename) {
        if (!filename) return '';
        const path = `${this.getIconFolderPath()}/${filename}`;
        return this.app.vault.adapter.getResourcePath(path);
    }

    async scanVaultForFolderIcons() {
        this.folderIconsCache = {};
        await this.scanFolderRecursive('');
    }

    async scanFolderRecursive(folderPath) {
        const list = await this.app.vault.adapter.list(folderPath);
        
        // Skip scanning our own icon storage directory to save cycles
        if (folderPath === this.getIconFolderPath()) return;

        const configFilePath = folderPath ? `${folderPath}/.folder-icon.json` : '.folder-icon.json';
        if (await this.app.vault.adapter.exists(configFilePath)) {
            try {
                const data = JSON.parse(await this.app.vault.adapter.read(configFilePath));
                if (data && data.iconName) {
                    this.folderIconsCache[folderPath || '/'] = data.iconName;
                }
            } catch(e) {}
        }

        for (let subFolder of list.folders) {
            await this.scanFolderRecursive(subFolder);
        }
    }

    async generateDynamicCssSnippet() {
        let cssContent = `/* Automatically generated by Notion-like Icons Plugin */\n`;
        cssContent += `
span[data-shortcode] {
    display: inline-flex;
    align-items: center;
    color: transparent !important;
    font-size: 0 !important;
    position: relative;
    vertical-align: middle;
}
span[data-shortcode]::before {
    content: "";
    display: inline-block;
    background-size: contain;
    background-repeat: no-repeat;
    background-position: center;
    border-radius: 4px;
}\n`;

        Object.keys(this.settings.icons).forEach((name) => {
            const filename = this.settings.icons[name];
            const localSrc = this.getIconSrcPath(filename);
            cssContent += `span[data-shortcode="${name}"]::before { background-image: url("${localSrc}"); width: 18px; height: 18px; margin-right: 4px; }\n`;
        });

        const snippetPath = `${this.app.vault.configDir}/snippets/notion-live-icons.css`;
        if (!(await this.app.vault.adapter.exists(`${this.app.vault.configDir}/snippets`))) {
            await this.app.vault.adapter.mkdir(`${this.app.vault.configDir}/snippets`);
        }
        await this.app.vault.adapter.write(snippetPath, cssContent);
        this.app.customCss?.setCssEnabledStatus?.("notion-live-icons", true);
        this.app.customCss?.requestLoadSnippets?.();
    }

    applyShortcodeAttributes(element) {
        if (!element) return;
        const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT, null, false);
        let textNode;
        const regex = /:([a-zA-Z0-9_-]+):/g;
        const nodesToReplace = [];

        while (textNode = walker.nextNode()) {
            if (regex.test(textNode.nodeValue)) {
                if (textNode.parentElement && (
                    textNode.parentElement.closest('.modal') || 
                    textNode.parentElement.closest('code') ||
                    textNode.parentElement.hasAttribute('data-shortcode') ||
                    textNode.parentElement.classList.contains('inline-title') ||
                    textNode.parentElement.classList.contains('notion-sidebar-icon')
                )) {
                    continue;
                }
                nodesToReplace.push(textNode);
            }
            regex.lastIndex = 0; 
        }

        nodesToReplace.forEach(node => {
            const text = node.nodeValue;
            const parent = node.parentElement;
            if (!parent) return;

            const matches = [...text.matchAll(regex)];
            const fragment = document.createDocumentFragment();
            let lastIndex = 0;
            let hasValidMatch = false;

            matches.forEach(match => {
                const iconName = match[1];
                const fullShortcode = match[0];
                const matchIndex = match.index;

                if (matchIndex > lastIndex) {
                    fragment.appendChild(document.createTextNode(text.substring(lastIndex, matchIndex)));
                }

                if (this.settings.icons[iconName]) {
                    hasValidMatch = true;
                    const insideBasesCell = parent.closest('td') || parent.closest('.metadata-property') || parent.closest('.db-folder');
                    
                    if (insideBasesCell) {
                        const img = document.createElement('img');
                        img.src = this.getIconSrcPath(this.settings.icons[iconName]);
                        img.style.width = "16px"; img.style.height = "16px";
                        img.style.objectFit = "contain"; img.style.display = "inline-block";
                        img.style.verticalAlign = "middle"; img.style.marginRight = "4px";
                        fragment.appendChild(img);
                    } else {
                        const span = document.createElement('span');
                        span.setAttribute('data-shortcode', iconName);
                        span.textContent = fullShortcode;
                        fragment.appendChild(span);
                    }
                } else {
                    fragment.appendChild(document.createTextNode(fullShortcode));
                }
                lastIndex = matchIndex + fullShortcode.length;
            });

            if (lastIndex < text.length) {
                fragment.appendChild(document.createTextNode(text.substring(lastIndex)));
            }
            if (hasValidMatch) {
                parent.replaceChild(fragment, node);
            }
        });
    }

    refreshAllDisplays() {
        this.renderIconArea();
        this.renderFileExplorerIcons();
        this.applyShortcodeAttributes(document.body);
    }

    async assignIconToNote(file, iconName) {
        await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
            frontmatter['notion-like-icon'] = `:${iconName}:`;
        });
        this.refreshAllDisplays();
    }

    async removeIconFromNote(file) {
        await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
            delete frontmatter['notion-like-icon'];
        });
        this.refreshAllDisplays();
    }

    async assignIconToFolder(folderPath, iconName) {
        const cacheKey = folderPath || '/';
        this.folderIconsCache[cacheKey] = iconName;

        const configFilePath = folderPath ? `${folderPath}/.folder-icon.json` : '.folder-icon.json';
        const content = JSON.stringify({ iconName: iconName }, null, 2);
        
        await this.app.vault.adapter.write(configFilePath, content);
        this.refreshAllDisplays();
    }

    async removeIconFromFolder(folderPath) {
        const cacheKey = folderPath || '/';
        delete this.folderIconsCache[cacheKey];

        const configFilePath = folderPath ? `${folderPath}/.folder-icon.json` : '.folder-icon.json';
        if (await this.app.vault.adapter.exists(configFilePath)) {
            await this.app.vault.adapter.remove(configFilePath);
        }
        this.refreshAllDisplays();
    }

    renderIconArea() {
        const activeView = this.app.workspace.getActiveViewOfType(MarkdownView);
        if (!activeView || !activeView.file) return;

        const file = activeView.file;
        const cache = this.app.metadataCache.getFileCache(file);
        const iconPropValue = cache?.frontmatter?.['notion-like-icon'] || '';

        const existingWrapper = activeView.containerEl.querySelector('.notion-icon-wrapper');
        if (existingWrapper) existingWrapper.remove();

        const titleContainer = activeView.containerEl.querySelector('.inline-title');
        if (!titleContainer || !titleContainer.parentElement) return;

        const wrapper = document.createElement('div');
        wrapper.className = 'notion-icon-wrapper';
        const iconName = iconPropValue.replace(/:/g, '').trim();

        if (iconName && this.settings.icons[iconName]) {
            const iconContainer = wrapper.createEl('div', { cls: 'notion-icon-container' });
            const iconImg = document.createElement('img');
            iconImg.src = this.getIconSrcPath(this.settings.icons[iconName]);
            iconImg.className = 'notion-active-icon';
            
            iconImg.addEventListener('click', () => {
                new UniversalIconPickerModal(this.app, this, { type: 'note', target: file }).open();
            });
            iconContainer.appendChild(iconImg);
        } else {
            const addBtn = document.createElement('button');
            addBtn.className = 'notion-add-icon-btn';
            addBtn.innerHTML = '<span>➕</span> Add icon';
            addBtn.addEventListener('click', () => {
                new UniversalIconPickerModal(this.app, this, { type: 'note', target: file }).open();
            });
            wrapper.appendChild(addBtn);
        }
        titleContainer.parentElement.insertBefore(wrapper, titleContainer);
    }

    renderFileExplorerIcons() {
        const fileExplorerLeaves = this.app.workspace.getLeavesOfType('file-explorer');
        fileExplorerLeaves.forEach((leaf) => {
            const fileItems = leaf.view.fileItems; if (!fileItems) return;
            Object.keys(fileItems).forEach((path) => {
                const item = fileItems[path]; if (!item || !item.el) return;
                
                const oldIcon = item.el.querySelector('.notion-sidebar-icon');
                if (oldIcon) oldIcon.remove();

                const abstractFile = this.app.vault.getAbstractFileByPath(path);
                if (!abstractFile) return;

                let iconName = '';

                if (abstractFile.children) {
                    const cacheKey = path || '/';
                    iconName = this.folderIconsCache[cacheKey] || '';
                } else {
                    const cache = this.app.metadataCache.getCache(path);
                    const rawProp = cache?.frontmatter?.['notion-like-icon'] || '';
                    iconName = rawProp.replace(/:/g, '').trim();
                }

                if (iconName && this.settings.icons[iconName]) {
                    const iconImg = document.createElement('img');
                    iconImg.src = this.getIconSrcPath(this.settings.icons[iconName]);
                    iconImg.className = 'notion-sidebar-icon';
                    
                    const titleEl = item.el.querySelector('.nav-folder-title-content') || item.el.querySelector('.nav-file-title-content');
                    if (titleEl) titleEl.parentElement.insertBefore(iconImg, titleEl);
                }
            });
        });
    }

    async processImageBlob(blob, name) {
        if (!ALLOWED_IMAGE_TYPES.includes(blob.type)) throw new Error("InvalidFormat");
        const img = new Image();
        img.src = URL.createObjectURL(blob);
        await new Promise((resolve, reject) => {
            img.onload = resolve; img.onerror = () => reject(new Error("CorruptedImage"));
        });

        const canvas = document.createElement('canvas');
        canvas.width = 64; canvas.height = 64;
        const ctx = canvas.getContext('2d');
        if (ctx) {
            ctx.drawImage(img, 0, 0, 64, 64);
            const targetBlob = await new Promise(res => canvas.toBlob(res, 'image/png'));
            const arrayBuffer = await targetBlob.arrayBuffer();
            const cleanName = name.replace(/[^a-z0-9_-]/gi, '_').toLowerCase();
            const filename = `${cleanName}.png`;
            const fullPath = `${this.getIconFolderPath()}/${filename}`;
            await this.app.vault.adapter.writeBinary(fullPath, arrayBuffer);
            URL.revokeObjectURL(img.src);
            this.settings.icons[cleanName] = filename;
            await this.saveSettings();
            await this.generateDynamicCssSnippet(); 
            return cleanName;
        }
        throw new Error("CanvasFailure");
    }

    async downloadAndSaveIcon(url, name) {
        url = url.trim();
        if (!url.startsWith('http://') && !url.startsWith('https://')) {
            return { success: false, message: "❌ Invalid URL protocol." };
        }
        const timeoutPromise = new Promise((_, reject) => setTimeout(() => reject(new Error("Timeout")), 7000));
        try {
            const response = await Promise.race([requestUrl({ url: url }), timeoutPromise]);
            const contentType = (response.headers['content-type'] || response.headers['Content-Type'] || '').toLowerCase();
            if (contentType.includes('text/html') || !ALLOWED_IMAGE_TYPES.some(t => contentType.includes(t))) {
                throw new Error("NotAnImage");
            }
            const cleanMimeType = ALLOWED_IMAGE_TYPES.find(t => contentType.includes(t)) || 'image/png';
            const blob = new Blob([response.arrayBuffer], { type: cleanMimeType });
            const savedName = await this.processImageBlob(blob, name);
            return { success: true, name: savedName };
        } catch (error) {
            return { success: false, message: "⚠️ Failed to fetch image online." };
        }
    }

    async renameIconShortcode(oldName, newName) {
        newName = newName.replace(/[^a-z0-9_-]/gi, '_').toLowerCase().trim();
        if (!newName || oldName === newName) return { success: false };
        if (this.settings.icons[newName]) return { success: false, message: "❌ Code already exists!" };

        const filename = this.settings.icons[oldName];
        this.settings.icons[newName] = filename;
        delete this.settings.icons[oldName];
        await this.saveSettings();
        await this.generateDynamicCssSnippet();
        return { success: true };
    }

    async removeIconFromLibrary(name) {
        const filename = this.settings.icons[name];
        if (filename) {
            const fullPath = `${this.getIconFolderPath()}/${filename}`;
            try {
                if (await this.app.vault.adapter.exists(fullPath)) {
                    await this.app.vault.adapter.remove(fullPath);
                }
            } catch (e) {}
        }
        delete this.settings.icons[name];
        await this.saveSettings();
        await this.generateDynamicCssSnippet(); 
    }

    async loadSettings() { this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData()); }
    async saveSettings() { await this.saveData(this.settings); }
};

// --- GLOBAL SHORTCODES MANAGER ---
class CentralIconLibraryModal extends Modal {
    constructor(app, plugin) {
        super(app);
        this.plugin = plugin;
        this.jszipInstance = null;
    }

    async getJSZip() {
        if (this.jszipInstance) return this.jszipInstance;
        if (window.JSZip) { this.jszipInstance = window.JSZip; return this.jszipInstance; }
        const script = document.createElement('script');
        script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js';
        document.head.appendChild(script);
        await new Promise((resolve) => script.onload = resolve);
        this.jszipInstance = window.JSZip; return this.jszipInstance;
    }

    getMimeTypeByExtension(filename) {
        const ext = filename.split('.').pop().toLowerCase();
        if (ext === 'png') return 'image/png';
        if (ext === 'jpg' || ext === 'jpeg') return 'image/jpeg';
        if (ext === 'webp') return 'image/webp';
        return '';
    }

    onOpen() {
        const { contentEl } = this;
        contentEl.createEl('h2', { text: 'Global Icon Library Manager' });

        const errorDiv = contentEl.createEl('div', { style: 'color: var(--text-error); margin-bottom: 12px; display: none;' });
        contentEl.appendChild(errorDiv);

        const currentFile = this.app.workspace.getActiveFile();
        if (currentFile) {
            const shortcutBtn = contentEl.createEl('button', { text: `🎯 Target Open Note (${currentFile.basename})`, style: 'margin-bottom:15px; width:100%; font-weight:bold;' });
            shortcutBtn.addEventListener('click', () => {
                this.close();
                new UniversalIconPickerModal(this.app, this.plugin, { type: 'note', target: currentFile }).open();
            });
        }

        const searchInput = contentEl.createEl('input', { style: 'width:100%; margin-bottom:15px; padding:8px; border-radius:6px; border:1px solid var(--border-color); background:var(--background-primary)' });
        searchInput.placeholder = '🔍 Search active library codes...';

        const grid = contentEl.createEl('div', { cls: 'icon-grid-container' });

        const rebuildLibraryGrid = () => {
            grid.empty();
            const savedIcons = Object.keys(this.plugin.settings.icons);
            if (savedIcons.length === 0) {
                grid.createEl('p', { text: 'No custom icons saved yet.', cls: 'icon-empty-text' });
                return;
            }

            savedIcons.forEach((name) => {
                const item = grid.createEl('div', { cls: 'icon-grid-item global-card' });
                item.setAttribute('data-name', name.toLowerCase());

                const img = item.createEl('img');
                img.src = this.plugin.getIconSrcPath(this.plugin.settings.icons[name]);
                
                const labelContainer = item.createEl('div', { cls: 'card-label-wrapper' });
                const nameSpan = labelContainer.createEl('span', { text: `:${name}:`, cls: 'card-shortcode-label' });
                
                const editInputBox = labelContainer.createEl('input', { type: 'text', value: name, cls: 'card-edit-input' });
                const saveRenameBtn = labelContainer.createEl('button', { text: '✓', cls: 'card-edit-save-btn' });

                const actionsBox = item.createEl('div', { cls: 'card-actions-overlay' });

                const cpBtn = actionsBox.createEl('button', { text: '📋', title: 'Copy shortcode' });
                cpBtn.addEventListener('click', (e) => {
                    e.stopPropagation();
                    navigator.clipboard.writeText(`:${name}:`);
                });

                const editBtn = actionsBox.createEl('button', { text: '✏️', title: 'Rename code trigger' });
                editBtn.addEventListener('click', (e) => {
                    e.stopPropagation();
                    labelContainer.classList.add('is-editing');
                    editInputBox.focus();
                    editInputBox.select();
                });

                const delBtn = actionsBox.createEl('button', { text: '✕', title: 'Delete icon' });
                delBtn.style.color = 'var(--text-error)';
                delBtn.addEventListener('click', async (e) => {
                    e.stopPropagation();
                    if (confirm(`Permanently wipe "${name}" from libraries?`)) {
                        await this.plugin.removeIconFromLibrary(name);
                        rebuildLibraryGrid();
                        this.plugin.refreshAllDisplays();
                    }
                });

                saveRenameBtn.addEventListener('click', async (e) => {
                    e.stopPropagation();
                    const newCodeValue = editInputBox.value.trim();
                    if (newCodeValue && newCodeValue !== name) {
                        const res = await this.plugin.renameIconShortcode(name, newCodeValue);
                        if (res && res.message) {
                            errorDiv.innerText = res.message; errorDiv.style.display = 'block';
                        } else {
                            errorDiv.style.display = 'none';
                        }
                    }
                    rebuildLibraryGrid();
                    this.plugin.refreshAllDisplays();
                });

                editInputBox.addEventListener('keydown', async (e) => {
                    if (e.key === 'Enter') {
                        e.preventDefault();
                        saveRenameBtn.click();
                    } else if (e.key === 'Escape') {
                        rebuildLibraryGrid();
                    }
                });
            });
        };
        rebuildLibraryGrid();

        searchInput.addEventListener('input', (e) => {
            const query = e.target.value.toLowerCase().trim();
            const items = grid.querySelectorAll('.icon-grid-item');
            items.forEach((item) => {
                const nameAttr = item.getAttribute('data-name') || '';
                item.style.display = nameAttr.includes(query) ? 'flex' : 'none';
            });
        });

        contentEl.createEl('hr');
        contentEl.createEl('h3', { text: 'Import Asset Files' });
        const dropZone = contentEl.createEl('div', { cls: 'icon-drop-zone', text: '📥 Drag image file or a compressed .zip package here' });
        
        dropZone.addEventListener('dragover', (e) => { e.preventDefault(); dropZone.style.borderColor = 'var(--interactive-accent)'; });
        dropZone.addEventListener('dragleave', () => { dropZone.style.borderColor = 'var(--border-color)'; });
        dropZone.addEventListener('drop', async (e) => {
            e.preventDefault(); dropZone.style.borderColor = 'var(--border-color)'; errorDiv.style.display = 'none';
            const dropFile = e.dataTransfer.files[0]; if (!dropFile) return;

            if (dropFile.name.endsWith('.zip')) {
                dropZone.innerText = '⚙️ Unpacking entries...';
                try {
                    const JSZipLib = await this.getJSZip();
                    const zip = await JSZipLib.loadAsync(dropFile);
                    let count = 0;
                    for (const relPath of Object.keys(zip.files)) {
                        const entry = zip.files[relPath]; if (entry.dir) continue;
                        const mime = this.getMimeTypeByExtension(entry.name); if (!mime) continue;
                        const baseName = entry.name.split('/').pop().replace(/\.[^/.]+$/, "").toLowerCase();
                        const buf = await entry.async('arraybuffer');
                        await this.plugin.processImageBlob(new Blob([buf], { type: mime }), baseName);
                        count++;
                    }
                    rebuildLibraryGrid(); this.plugin.refreshAllDisplays();
                    dropZone.innerText = `✅ Loaded ${count} shortcuts!`;
                } catch (err) { errorDiv.innerText = "❌ ZIP extraction crash."; errorDiv.style.display = 'block'; }
                return;
            }

            const mime = this.getMimeTypeByExtension(dropFile.name);
            if (mime || ALLOWED_IMAGE_TYPES.includes(dropFile.type)) {
                const cleanName = dropFile.name.replace(/\.[^/.]+$/, "").toLowerCase().replace(/[^a-z0-9_-]/gi, '_');
                await this.plugin.processImageBlob(dropFile, cleanName);
                rebuildLibraryGrid(); this.plugin.refreshAllDisplays();
                dropZone.innerText = `✅ Registered :${cleanName}:`;
            }
        });

        let newName = ''; let newUrl = '';
        new Setting(contentEl).setName('Custom Asset Name').addText(t => t.setPlaceholder('e.g., doraemon').onChange(v => newName = v));
        new Setting(contentEl).setName('Direct Image URL').addText(t => t.setPlaceholder('https://.../img.png').onChange(v => newUrl = v));
        new Setting(contentEl).addButton(btn => btn.setButtonText('Download Asset').setCta().onClick(async () => {
            if (!newName || !newUrl) return;
            btn.setDisabled(true); btn.setButtonText('Downloading...');
            const res = await this.plugin.downloadAndSaveIcon(newUrl, newName);
            if (res.success) {
                rebuildLibraryGrid(); this.plugin.refreshAllDisplays();
                btn.setDisabled(false); btn.setButtonText('Download Asset');
            } else {
                errorDiv.innerText = res.message; errorDiv.style.display = 'block'; btn.setDisabled(false);
            }
        }));
    }
    onClose() { this.contentEl.empty(); }
}

// --- UNIVERSAL TARGET ICON PICKER MODAL ---
class UniversalIconPickerModal extends Modal {
    constructor(app, plugin, context) {
        super(app);
        this.plugin = plugin;
        this.context = context; // Context: { type: 'note' | 'folder', target: TFile | TFolder }
        this.shouldClearIcon = false;

        if (this.context.type === 'folder') {
            const cacheKey = this.context.target.path || '/';
            this.originalIconName = this.plugin.folderIconsCache[cacheKey] || '';
        } else {
            const cache = this.app.metadataCache.getFileCache(this.context.target);
            const currentRaw = cache?.frontmatter?.['notion-like-icon'] || '';
            this.originalIconName = currentRaw.replace(/:/g, '').trim();
        }
        this.selectedIconName = this.originalIconName;
    }

    onOpen() {
        const { contentEl } = this;
        const targetLabel = this.context.type === 'folder' ? `Folder: ${this.context.target.name}` : `Note: ${this.context.target.basename}`;
        contentEl.createEl('h2', { text: `Configure Icon (${targetLabel})`, cls: 'icon-modal-title' });

        const previewHeader = contentEl.createEl('div', { style: 'display:flex; align-items:center; gap:15px; padding:12px; background:var(--background-primary-alt); border-radius:8px; margin-bottom:15px; border:1px solid var(--border-color);' });
        const previewImg = previewHeader.createEl('img', { style: 'width:48px; height:48px; object-fit:contain; border-radius:6px;' });
        const previewText = previewHeader.createEl('div', { style: 'font-size:14px;' });

        const updatePreviewDisplay = () => {
            if (this.shouldClearIcon) {
                previewImg.style.display = 'none';
                previewText.innerHTML = "<b>Status:</b> Icon will be <b>Cleared</b>";
            } else if (this.selectedIconName && this.plugin.settings.icons[this.selectedIconName]) {
                previewImg.src = this.plugin.getIconSrcPath(this.plugin.settings.icons[this.selectedIconName]);
                previewImg.style.display = 'block';
                previewText.innerHTML = `<b>Selected Preview:</b> <code>:${this.selectedIconName}:</code>`;
            } else {
                previewImg.style.display = 'none';
                previewText.innerHTML = "<b>Status:</b> No icon configured for this element";
            }
        };
        updatePreviewDisplay();

        const searchInput = contentEl.createEl('input', { style: 'width:100%; margin-bottom:10px; padding:8px; border-radius:6px; border:1px solid var(--border-color); background:var(--background-primary)' });
        searchInput.placeholder = '🔍 Search saved shortcuts...';

        contentEl.createEl('h3', { text: 'Click an item below to apply' });
        const grid = contentEl.createEl('div', { cls: 'icon-grid-container' });

        const rebuildLibraryGrid = () => {
            grid.empty();
            const savedIcons = Object.keys(this.plugin.settings.icons);
            if (savedIcons.length === 0) {
                grid.createEl('p', { text: 'No options saved inside the system. Run the Global Manager from the side panel ribbon to insert assets first.', cls: 'icon-empty-text' });
                return;
            }

            savedIcons.forEach((name) => {
                const item = grid.createEl('div', { cls: 'icon-grid-item note-card' });
                item.setAttribute('data-name', name.toLowerCase());

                if (name === this.selectedIconName && !this.shouldClearIcon) {
                    item.style.border = '2px solid var(--interactive-accent)';
                    item.style.background = 'var(--background-modifier-hover)';
                }

                const img = item.createEl('img');
                img.src = this.plugin.getIconSrcPath(this.plugin.settings.icons[name]);
                item.createEl('span', { text: `:${name}:` });

                item.addEventListener('click', () => {
                    this.selectedIconName = name;
                    this.shouldClearIcon = false;
                    updatePreviewDisplay();
                    rebuildLibraryGrid();
                });
            });
        };
        rebuildLibraryGrid();

        searchInput.addEventListener('input', (e) => {
            const query = e.target.value.toLowerCase().trim();
            const items = grid.querySelectorAll('.icon-grid-item');
            items.forEach((item) => {
                const nameAttr = item.getAttribute('data-name') || '';
                item.style.display = nameAttr.includes(query) ? 'flex' : 'none';
            });
        });

        contentEl.createEl('hr');
        const footer = contentEl.createEl('div', { style: 'display:flex; justify-content:space-between; margin-top:20px;' });
        
        const clearBtn = footer.createEl('button', { cls: 'mod-warning', text: 'Clear Icon' });
        clearBtn.style.padding = '8px 14px';
        clearBtn.addEventListener('click', () => {
            this.shouldClearIcon = true; this.selectedIconName = '';
            updatePreviewDisplay(); rebuildLibraryGrid();
        });

        const saveBtn = footer.createEl('button', { cls: 'mod-cta', text: 'Accept & Apply Changes' });
        saveBtn.style.padding = '8px 18px'; saveBtn.style.fontWeight = 'bold';
        saveBtn.addEventListener('click', async () => {
            if (this.context.type === 'folder') {
                if (this.shouldClearIcon) {
                    await this.plugin.removeIconFromFolder(this.context.target.path);
                } else if (this.selectedIconName) {
                    await this.plugin.assignIconToFolder(this.context.target.path, this.selectedIconName);
                }
            } else {
                if (this.shouldClearIcon) {
                    await this.plugin.removeIconFromNote(this.context.target);
                } else if (this.selectedIconName) {
                    await this.plugin.assignIconToNote(this.context.target, this.selectedIconName);
                }
            }
            this.close();
        });
    }

    onClose() { this.contentEl.empty(); }
}